import { HeroDefinition, EnemyDefinition, RogueliteSkill, StageDefinition, GameSaveData, RestEventChoice } from './types';

// ===== HEROES =====
export const HEROES: Record<string, HeroDefinition> = {
  ironclad: {
    id: 'ironclad',
    name: 'Ironclad',
    nameKo: '아이언클래드',
    class: 'tank',
    stars: 2,
    position: 'front',
    baseStats: { hp: 600, atk: 45, def: 80, spd: 35 },
    emoji: '🛡️',
    basicSkill: {
      id: 'shield_bash',
      name: 'Shield Bash',
      nameKo: '방패 강타',
      type: 'damage',
      targetType: 'single',
      targetTeam: 'enemy',
      multiplier: 0.8,
      effects: [{ type: 'taunt', value: 1, duration: 1 }],
      description: 'Strikes enemy and taunts for 1 turn',
      isUltimate: false,
    },
    ultimateSkill: {
      id: 'iron_fortress',
      name: 'Iron Fortress',
      nameKo: '철벽 수호',
      type: 'buff',
      targetType: 'aoe',
      targetTeam: 'ally',
      multiplier: 0.2, // self heal 20% maxHP
      effects: [{ type: 'def_up', value: 0.3, duration: 2 }],
      description: 'DEF UP for all allies + self heal 20%',
      isUltimate: true,
    },
  },
  blade: {
    id: 'blade',
    name: 'Blade',
    nameKo: '블레이드',
    class: 'warrior',
    stars: 3,
    position: 'front',
    baseStats: { hp: 420, atk: 95, def: 50, spd: 50 },
    emoji: '⚔️',
    basicSkill: {
      id: 'slash',
      name: 'Slash',
      nameKo: '베기',
      type: 'damage',
      targetType: 'single',
      targetTeam: 'enemy',
      multiplier: 1.2,
      description: 'Strong physical attack on single enemy',
      isUltimate: false,
    },
    ultimateSkill: {
      id: 'storm_slash',
      name: 'Storm Slash',
      nameKo: '폭풍 참격',
      type: 'damage',
      targetType: 'front_row',
      targetTeam: 'enemy',
      multiplier: 0.8,
      effects: [{ type: 'bleed', value: 0.06, duration: 3 }],
      description: 'AoE front row damage + bleed',
      isUltimate: true,
    },
  },
  silvana: {
    id: 'silvana',
    name: 'Silvana',
    nameKo: '실바나',
    class: 'ranger',
    stars: 3,
    position: 'back',
    baseStats: { hp: 320, atk: 110, def: 30, spd: 65 },
    emoji: '🏹',
    basicSkill: {
      id: 'aimed_shot',
      name: 'Aimed Shot',
      nameKo: '조준 사격',
      type: 'damage',
      targetType: 'single',
      targetTeam: 'enemy',
      multiplier: 1.3,
      description: 'High damage shot targeting lowest HP enemy',
      isUltimate: false,
      targetLowestHp: true,
    },
    ultimateSkill: {
      id: 'arrow_rain',
      name: 'Arrow Rain',
      nameKo: '화살 비',
      type: 'damage',
      targetType: 'aoe',
      targetTeam: 'enemy',
      multiplier: 0.7,
      description: 'AoE damage to all enemies',
      isUltimate: true,
    },
  },
  ignis: {
    id: 'ignis',
    name: 'Ignis',
    nameKo: '이그니스',
    class: 'mage',
    stars: 4,
    position: 'back',
    baseStats: { hp: 280, atk: 130, def: 25, spd: 55 },
    emoji: '🔮',
    basicSkill: {
      id: 'firebolt',
      name: 'Firebolt',
      nameKo: '파이어볼트',
      type: 'damage',
      targetType: 'single',
      targetTeam: 'enemy',
      multiplier: 1.1,
      effects: [{ type: 'bleed', value: 0.06, duration: 3, chance: 0.5 }],
      description: 'Fire damage with 50% chance burn',
      isUltimate: false,
    },
    ultimateSkill: {
      id: 'meteor_strike',
      name: 'Meteor Strike',
      nameKo: '메테오 스트라이크',
      type: 'damage',
      targetType: 'aoe',
      targetTeam: 'enemy',
      multiplier: 1.0,
      effects: [{ type: 'def_down', value: 0.25, duration: 2 }],
      description: 'AoE magic damage + DEF DOWN',
      isUltimate: true,
    },
  },
  lumina: {
    id: 'lumina',
    name: 'Lumina',
    nameKo: '루미나',
    class: 'healer',
    stars: 2,
    position: 'back',
    baseStats: { hp: 380, atk: 70, def: 40, spd: 45 },
    emoji: '✨',
    basicSkill: {
      id: 'light_heal',
      name: 'Light Heal',
      nameKo: '빛의 치유',
      type: 'heal',
      targetType: 'single',
      targetTeam: 'ally',
      multiplier: 1.5,
      description: 'Heals ally with lowest HP',
      isUltimate: false,
      targetLowestHp: true,
    },
    ultimateSkill: {
      id: 'holy_blessing',
      name: 'Holy Blessing',
      nameKo: '성스러운 축복',
      type: 'heal',
      targetType: 'aoe',
      targetTeam: 'ally',
      multiplier: 1.0,
      effects: [{ type: 'regen', value: 0.08, duration: 3 }],
      description: 'AoE heal + regen',
      isUltimate: true,
    },
  },
  shadow: {
    id: 'shadow',
    name: 'Shadow',
    nameKo: '쉐도우',
    class: 'assassin',
    stars: 5,
    position: 'front',
    baseStats: { hp: 340, atk: 105, def: 35, spd: 75 },
    emoji: '🗡️',
    basicSkill: {
      id: 'shadow_slash',
      name: 'Shadow Slash',
      nameKo: '그림자 베기',
      type: 'damage',
      targetType: 'single',
      targetTeam: 'enemy',
      multiplier: 1.4,
      description: 'Targets lowest HP enemy',
      isUltimate: false,
      targetLowestHp: true,
    },
    ultimateSkill: {
      id: 'assassinate',
      name: 'Assassinate',
      nameKo: '암살',
      type: 'damage',
      targetType: 'single',
      targetTeam: 'enemy',
      multiplier: 2.5,
      description: 'Ultra high damage to lowest HP enemy',
      isUltimate: true,
      targetLowestHp: true,
    },
  },
};

// ===== ENEMIES =====
export const ENEMIES: Record<string, EnemyDefinition> = {
  goblin_soldier: {
    id: 'goblin_soldier',
    name: 'Goblin Soldier',
    nameKo: '고블린 병사',
    type: 'minion',
    baseStats: { hp: 180, atk: 40, def: 20, spd: 40 },
    emoji: '👺',
    basicSkill: {
      id: 'stab',
      name: 'Stab',
      nameKo: '찌르기',
      type: 'damage',
      targetType: 'single',
      targetTeam: 'enemy',
      multiplier: 1.0,
      description: 'Basic stab attack',
      isUltimate: false,
    },
  },
  goblin_archer: {
    id: 'goblin_archer',
    name: 'Goblin Archer',
    nameKo: '고블린 궁수',
    type: 'minion',
    baseStats: { hp: 140, atk: 55, def: 15, spd: 50 },
    emoji: '🏹',
    basicSkill: {
      id: 'poison_arrow',
      name: 'Poison Arrow',
      nameKo: '독화살',
      type: 'damage',
      targetType: 'single',
      targetTeam: 'enemy',
      multiplier: 0.9,
      effects: [{ type: 'bleed', value: 0.06, duration: 3, chance: 0.3 }],
      description: 'Arrow with 30% poison chance',
      isUltimate: false,
    },
  },
  skeleton_warrior: {
    id: 'skeleton_warrior',
    name: 'Skeleton Warrior',
    nameKo: '해골 전사',
    type: 'minion',
    baseStats: { hp: 220, atk: 50, def: 35, spd: 30 },
    emoji: '💀',
    basicSkill: {
      id: 'bone_axe',
      name: 'Bone Axe',
      nameKo: '뼈도끼',
      type: 'damage',
      targetType: 'single',
      targetTeam: 'enemy',
      multiplier: 1.1,
      description: 'Heavy axe attack',
      isUltimate: false,
    },
  },
  dark_mage: {
    id: 'dark_mage',
    name: 'Dark Mage',
    nameKo: '다크 메이지',
    type: 'elite',
    baseStats: { hp: 300, atk: 80, def: 25, spd: 55 },
    emoji: '🧙',
    basicSkill: {
      id: 'dark_arrow',
      name: 'Dark Arrow',
      nameKo: '암흑 화살',
      type: 'damage',
      targetType: 'single',
      targetTeam: 'enemy',
      multiplier: 1.2,
      description: 'Dark magic projectile',
      isUltimate: false,
    },
    ultimateSkill: {
      id: 'curse',
      name: 'Curse',
      nameKo: '저주',
      type: 'debuff',
      targetType: 'single',
      targetTeam: 'enemy',
      multiplier: 0,
      effects: [{ type: 'atk_down', value: 0.25, duration: 2 }],
      description: 'ATK DOWN on single enemy',
      isUltimate: true,
    },
  },
  orc_berserker: {
    id: 'orc_berserker',
    name: 'Orc Berserker',
    nameKo: '오크 버서커',
    type: 'elite',
    baseStats: { hp: 500, atk: 70, def: 40, spd: 35 },
    emoji: '👹',
    basicSkill: {
      id: 'charge',
      name: 'Charge',
      nameKo: '돌진',
      type: 'damage',
      targetType: 'single',
      targetTeam: 'enemy',
      multiplier: 1.3,
      description: 'Powerful charge attack',
      isUltimate: false,
    },
    ultimateSkill: {
      id: 'berserk',
      name: 'Berserk',
      nameKo: '광폭화',
      type: 'buff',
      targetType: 'single',
      targetTeam: 'ally',
      multiplier: 0,
      effects: [{ type: 'atk_up', value: 0.3, duration: 2 }],
      description: 'Self ATK UP',
      isUltimate: true,
    },
  },
  vampire_lord: {
    id: 'vampire_lord',
    name: 'Vampire Lord',
    nameKo: '뱀파이어 로드',
    type: 'elite',
    baseStats: { hp: 400, atk: 75, def: 30, spd: 60 },
    emoji: '🧛',
    basicSkill: {
      id: 'blood_drain',
      name: 'Blood Drain',
      nameKo: '흡혈',
      type: 'damage_heal',
      targetType: 'single',
      targetTeam: 'enemy',
      multiplier: 1.0,
      description: 'Damage + heal 30% of damage dealt',
      isUltimate: false,
    },
    ultimateSkill: {
      id: 'bat_swarm',
      name: 'Bat Swarm',
      nameKo: '박쥐 떼',
      type: 'damage_heal',
      targetType: 'aoe',
      targetTeam: 'enemy',
      multiplier: 0.6,
      description: 'AoE damage + lifesteal',
      isUltimate: true,
    },
  },
  dungeon_lord: {
    id: 'dungeon_lord',
    name: 'Dungeon Lord',
    nameKo: '던전 로드',
    type: 'boss',
    baseStats: { hp: 1200, atk: 90, def: 60, spd: 45 },
    emoji: '👿',
    basicSkill: {
      id: 'earth_shatter',
      name: 'Earth Shatter',
      nameKo: '대지 분쇄',
      type: 'damage',
      targetType: 'front_row',
      targetTeam: 'enemy',
      multiplier: 1.2,
      description: 'AoE front row damage',
      isUltimate: false,
    },
    ultimateSkill: {
      id: 'doom_strike',
      name: 'Doom Strike',
      nameKo: '종말의 일격',
      type: 'damage',
      targetType: 'aoe',
      targetTeam: 'enemy',
      multiplier: 1.5,
      effects: [{ type: 'def_down', value: 0.25, duration: 2 }],
      description: 'AoE massive damage + DEF DOWN',
      isUltimate: true,
    },
  },
};

// ===== STAGE DEFINITIONS =====
export const STAGES: StageDefinition[] = [
  {
    stageNumber: 1,
    type: 'normal',
    enemies: [
      { enemyId: 'goblin_soldier', position: 'front' },
      { enemyId: 'goblin_soldier', position: 'front' },
      { enemyId: 'goblin_soldier', position: 'back' },
      { enemyId: 'goblin_archer', position: 'back' },
    ],
    scaling: { hp: 1.0, atk: 1.0, def: 1.0 },
  },
  {
    stageNumber: 2,
    type: 'normal',
    enemies: [
      { enemyId: 'goblin_soldier', position: 'front' },
      { enemyId: 'goblin_soldier', position: 'front' },
      { enemyId: 'goblin_archer', position: 'back' },
      { enemyId: 'goblin_archer', position: 'back' },
    ],
    scaling: { hp: 1.05, atk: 1.05, def: 1.0 },
  },
  {
    stageNumber: 3,
    type: 'normal',
    enemies: [
      { enemyId: 'skeleton_warrior', position: 'front' },
      { enemyId: 'skeleton_warrior', position: 'front' },
      { enemyId: 'goblin_archer', position: 'back' },
      { enemyId: 'goblin_archer', position: 'back' },
    ],
    scaling: { hp: 1.1, atk: 1.1, def: 1.05 },
  },
  {
    stageNumber: 4,
    type: 'rest',
    enemies: [],
    scaling: { hp: 1, atk: 1, def: 1 },
  },
  {
    stageNumber: 5,
    type: 'elite',
    enemies: [
      { enemyId: 'skeleton_warrior', position: 'front' },
      { enemyId: 'skeleton_warrior', position: 'front' },
      { enemyId: 'dark_mage', position: 'back' },
      { enemyId: 'goblin_archer', position: 'back' },
    ],
    scaling: { hp: 1.2, atk: 1.15, def: 1.1 },
  },
  {
    stageNumber: 6,
    type: 'normal',
    enemies: [
      { enemyId: 'skeleton_warrior', position: 'front' },
      { enemyId: 'skeleton_warrior', position: 'front' },
      { enemyId: 'skeleton_warrior', position: 'back' },
      { enemyId: 'goblin_soldier', position: 'back' },
    ],
    scaling: { hp: 1.15, atk: 1.1, def: 1.05 },
  },
  {
    stageNumber: 7,
    type: 'normal',
    enemies: [
      { enemyId: 'skeleton_warrior', position: 'front' },
      { enemyId: 'skeleton_warrior', position: 'front' },
      { enemyId: 'goblin_archer', position: 'back' },
      { enemyId: 'goblin_archer', position: 'back' },
    ],
    scaling: { hp: 1.2, atk: 1.15, def: 1.1 },
  },
  {
    stageNumber: 8,
    type: 'rest',
    enemies: [],
    scaling: { hp: 1, atk: 1, def: 1 },
  },
  {
    stageNumber: 9,
    type: 'elite',
    enemies: [
      { enemyId: 'orc_berserker', position: 'front' },
      { enemyId: 'skeleton_warrior', position: 'front' },
      { enemyId: 'vampire_lord', position: 'back' },
      { enemyId: 'dark_mage', position: 'back' },
    ],
    scaling: { hp: 1.35, atk: 1.25, def: 1.15 },
  },
  {
    stageNumber: 10,
    type: 'boss',
    enemies: [
      { enemyId: 'orc_berserker', position: 'front' },
      { enemyId: 'skeleton_warrior', position: 'front' },
      { enemyId: 'dungeon_lord', position: 'back' },
      { enemyId: 'dark_mage', position: 'back' },
    ],
    scaling: { hp: 1.5, atk: 1.3, def: 1.2 },
  },
];

// ===== ROGUELITE SKILLS (18) =====
export const ROGUELITE_SKILLS: RogueliteSkill[] = [
  // Common (8)
  {
    id: 'hp_training',
    name: 'HP Training',
    nameKo: '체력 단련',
    tier: 'common',
    description: 'All allies Max HP +10%',
    descriptionKo: '아군 전체 최대 HP +10%',
    effect: { type: 'stat_boost', stat: 'hp', value: 0.1, target: 'all' },
    emoji: '❤️',
  },
  {
    id: 'atk_training',
    name: 'ATK Training',
    nameKo: '공격 훈련',
    tier: 'common',
    description: 'All allies ATK +8%',
    descriptionKo: '아군 전체 ATK +8%',
    effect: { type: 'stat_boost', stat: 'atk', value: 0.08, target: 'all' },
    emoji: '⚔️',
  },
  {
    id: 'spd_training',
    name: 'SPD Training',
    nameKo: '민첩 훈련',
    tier: 'common',
    description: 'All allies SPD +10%',
    descriptionKo: '아군 전체 SPD +10%',
    effect: { type: 'stat_boost', stat: 'spd', value: 0.1, target: 'all' },
    emoji: '💨',
  },
  {
    id: 'def_training',
    name: 'DEF Training',
    nameKo: '방어 훈련',
    tier: 'common',
    description: 'All allies DEF +10%',
    descriptionKo: '아군 전체 DEF +10%',
    effect: { type: 'stat_boost', stat: 'def', value: 0.1, target: 'all' },
    emoji: '🛡️',
  },
  {
    id: 'first_aid',
    name: 'First Aid',
    nameKo: '응급 치료',
    tier: 'common',
    description: 'Heal all allies 10% HP at battle start',
    descriptionKo: '전투 시작 시 아군 전체 HP 10% 회복',
    effect: { type: 'battle_start_heal', value: 0.1 },
    emoji: '🩹',
  },
  {
    id: 'battle_instinct',
    name: 'Battle Instinct',
    nameKo: '전투 본능',
    tier: 'common',
    description: 'Ultimate gauge starts at +20',
    descriptionKo: '궁극기 게이지 시작값 +20',
    effect: { type: 'ultimate_gauge_start', value: 20 },
    emoji: '⚡',
  },
  {
    id: 'sturdy_armor',
    name: 'Sturdy Armor',
    nameKo: '견고한 갑옷',
    tier: 'common',
    description: 'Front row DEF +20%',
    descriptionKo: '앞줄 유닛 DEF +20%',
    effect: { type: 'stat_boost', stat: 'def', value: 0.2, target: 'front' },
    emoji: '🔰',
  },
  {
    id: 'sniper_training',
    name: 'Sniper Training',
    nameKo: '저격 훈련',
    tier: 'common',
    description: 'Back row ATK +12%',
    descriptionKo: '뒷줄 유닛 ATK +12%',
    effect: { type: 'stat_boost', stat: 'atk', value: 0.12, target: 'back' },
    emoji: '🎯',
  },

  // Rare (6)
  {
    id: 'vampiric_sigil',
    name: 'Vampiric Sigil',
    nameKo: '흡혈의 문장',
    tier: 'rare',
    description: 'Heal 12% of damage dealt',
    descriptionKo: '가하는 데미지의 12% HP 회복',
    effect: { type: 'lifesteal', value: 0.12 },
    emoji: '🩸',
  },
  {
    id: 'chain_counter',
    name: 'Chain Counter',
    nameKo: '연쇄 반격',
    tier: 'rare',
    description: '20% counter attack chance',
    descriptionKo: '피격 시 20% 확률 반격',
    effect: { type: 'counter_attack', chance: 0.2, multiplier: 0.5 },
    emoji: '↩️',
  },
  {
    id: 'executioner',
    name: "Executioner's Instinct",
    nameKo: '처형자의 본능',
    tier: 'rare',
    description: '+50% damage to enemies below 25% HP',
    descriptionKo: '적 HP 25% 이하 시 데미지 +50%',
    effect: { type: 'execute_bonus', hpThreshold: 0.25, damageBonus: 0.5 },
    emoji: '💀',
  },
  {
    id: 'war_cry',
    name: 'War Cry',
    nameKo: '전쟁의 함성',
    tier: 'rare',
    description: 'ATK UP for all allies at battle start',
    descriptionKo: '전투 시작 시 아군 전체 ATK UP 2턴',
    effect: { type: 'battle_start_buff', buffType: 'atk_up', duration: 2 },
    emoji: '📯',
  },
  {
    id: 'mana_overload',
    name: 'Mana Overload',
    nameKo: '마나 폭주',
    tier: 'rare',
    description: 'Ultimate damage/heal +30%',
    descriptionKo: '궁극기 데미지/힐 +30%',
    effect: { type: 'ultimate_damage_bonus', value: 0.3 },
    emoji: '💫',
  },
  {
    id: 'thorn_armor',
    name: 'Thorn Armor',
    nameKo: '가시 갑옷',
    tier: 'rare',
    description: 'Reflect 15% damage taken',
    descriptionKo: '피격 시 받은 데미지의 15% 반사',
    effect: { type: 'thorns', value: 0.15 },
    emoji: '🌵',
  },

  // Legendary (4)
  {
    id: 'undying_will',
    name: 'Undying Will',
    nameKo: '불사의 의지',
    tier: 'legendary',
    description: 'Revive once at 30% HP',
    descriptionKo: '런 중 1회 사망 시 HP 30% 부활',
    effect: { type: 'revive', hpPercent: 0.3 },
    emoji: '👼',
  },
  {
    id: 'berserker_soul',
    name: "Berserker's Soul",
    nameKo: '광전사의 혼',
    tier: 'legendary',
    description: 'ATK+40%, SPD+20% when below 50% HP',
    descriptionKo: 'HP 50% 이하 시 ATK+40%, SPD+20%',
    effect: { type: 'low_hp_boost', hpThreshold: 0.5, atkBonus: 0.4, spdBonus: 0.2 },
    emoji: '🔥',
  },
  {
    id: 'time_warp',
    name: 'Time Warp',
    nameKo: '시간 가속',
    tier: 'legendary',
    description: '15% chance for extra turn',
    descriptionKo: '행동 후 15% 확률 추가 턴',
    effect: { type: 'extra_turn_chance', chance: 0.15 },
    emoji: '⏰',
  },
  {
    id: 'soul_harvest',
    name: 'Soul Harvest',
    nameKo: '영혼 착취',
    tier: 'legendary',
    description: 'On kill: heal all 15% + gauge +15',
    descriptionKo: '적 처치 시 전체 HP 15% 회복 + 게이지 +15',
    effect: { type: 'on_kill_heal', healPercent: 0.15, gaugeBonus: 15 },
    emoji: '👻',
  },
];

// ===== STAGE REWARDS =====
export const STAGE_REWARDS: Record<number, { gold: number; soulStones: number; exp: number }> = {
  1: { gold: 50, soulStones: 30, exp: 20 },
  2: { gold: 50, soulStones: 30, exp: 20 },
  3: { gold: 50, soulStones: 30, exp: 20 },
  4: { gold: 0, soulStones: 50, exp: 0 },
  5: { gold: 80, soulStones: 50, exp: 40 },
  6: { gold: 80, soulStones: 50, exp: 40 },
  7: { gold: 80, soulStones: 50, exp: 40 },
  8: { gold: 0, soulStones: 50, exp: 0 },
  9: { gold: 120, soulStones: 60, exp: 50 },
  10: { gold: 150, soulStones: 80, exp: 60 },
};

export const CHAPTER_CLEAR_BONUS = { gold: 500, soulStones: 500 };

// ===== REST EVENT CHOICES =====
export const REST_CHOICES: RestEventChoice[] = [
  {
    id: 'rest',
    nameKo: '모닥불에서 쉬기',
    descriptionKo: '아군 전체 HP 30% 회복',
    effect: 'heal_30',
    emoji: '🔥',
  },
  {
    id: 'chest',
    nameKo: '비밀 상자 열기',
    descriptionKo: '스킬 1개 추가 획득 (랜덤)',
    effect: 'random_skill',
    emoji: '📦',
  },
];

// ===== GACHA CONFIG =====
export const GACHA_CONFIG = {
  singleCost: 300,
  tenPullCost: 2700,
  rates: {
    1: 0.40,
    2: 0.30,
    3: 0.20,
    4: 0.08,
    5: 0.02,
  } as Record<number, number>,
  tenPullGuaranteeMinStars: 3,
  duplicateFragments: { 1: 10, 2: 20, 3: 50, 4: 100, 5: 200 } as Record<number, number>,
};

// ===== LEVEL UP CONFIG =====
export const LEVEL_CONFIG = {
  maxLevel: 20,
  statGrowthPerLevel: 0.05,
  expTable: [
    0, 100, 250, 450, 750, 1100, 1500, 1950, 2450, 3000,
    3600, 4250, 4950, 5700, 6500, 7350, 8250, 9200, 10200, 11250,
  ],
  goldCostTable: [
    0, 50, 80, 120, 170, 230, 290, 350, 410, 470,
    530, 630, 730, 830, 930, 1030, 1180, 1330, 1480, 1630,
  ],
};

// ===== STAR MULTIPLIERS =====
export const STAR_MULTIPLIER: Record<number, number> = {
  1: 1.0,
  2: 1.2,
  3: 1.5,
  4: 1.9,
  5: 2.5,
};

// ===== BATTLE CONFIG =====
export const BATTLE_CONFIG = {
  maxRounds: 50,
  ultimateGaugeMax: 100,
  ultimateGaugeOnBasicSkill: 30,
  ultimateGaugeOnHit: 20,
  frontRowDefBonus: 0.1,
  animationSpeed: {
    '1x': {
      action: 800,
      popup: 600,
      turnDelay: 400,
      roundDelay: 500,
      death: 600,
      victory: 1200,
    },
    '2x': {
      action: 400,
      popup: 300,
      turnDelay: 200,
      roundDelay: 250,
      death: 300,
      victory: 600,
    },
  } as Record<string, Record<string, number>>,
};

// ===== INITIAL SAVE =====
export const INITIAL_SAVE: GameSaveData = {
  gold: 0,
  soulStones: 300,
  soulFragments: 0,
  heroes: [
    { id: 'ironclad', level: 1, exp: 0, owned: true },
    { id: 'lumina', level: 1, exp: 0, owned: true },
    { id: 'blade', level: 1, exp: 0, owned: false },
    { id: 'silvana', level: 1, exp: 0, owned: false },
    { id: 'ignis', level: 1, exp: 0, owned: false },
    { id: 'shadow', level: 1, exp: 0, owned: false },
  ],
  party: {
    frontLine: ['ironclad', null],
    backLine: ['lumina', null],
  },
  chapter1Cleared: false,
  totalRuns: 0,
};

// ===== COLOR PALETTE =====
export const COLORS = {
  primary: '#C8A84E',
  secondary: '#8B6914',
  bgBase: '#1A1A2E',
  bgSurface: '#16213E',
  accent: '#E94560',
  textPrimary: '#F5F5DC',
  textSecondary: '#A0A0B8',
  success: '#4ADE80',
  danger: '#EF4444',
  // Camp
  warmGlow: '#FF9F43',
  ember: '#E55039',
  // Dungeon
  dungeonDark: '#0D0D1A',
  stoneGray: '#3A3A4A',
  torchAmber: '#D4A017',
  // Star colors
  starColors: {
    1: '#9E9E9E',
    2: '#4CAF50',
    3: '#2196F3',
    4: '#9C27B0',
    5: '#FF9800',
  } as Record<number, string>,
  // Skill tier colors
  tierColors: {
    common: '#9E9E9E',
    rare: '#2196F3',
    legendary: '#C8A84E',
  } as Record<string, string>,
};

// ===== ASSET IMAGE MAPPING =====
export const CHARACTER_IMAGES: Record<string, string> = {
  // Heroes
  ironclad: '/assets/characters/hero_warrior.png',
  blade: '/assets/characters/hero_warrior.png',
  silvana: '/assets/characters/hero_archer.png',
  ignis: '/assets/characters/hero_mage.png',
  lumina: '/assets/characters/hero_healer.png',
  shadow: '/assets/characters/hero_assassin.png',
  // Enemies
  goblin_soldier: '/assets/characters/enemy_goblin.png',
  goblin_archer: '/assets/characters/enemy_goblin.png',
  skeleton_warrior: '/assets/characters/enemy_skeleton.png',
  dark_mage: '/assets/characters/enemy_darkKnight.png',
  orc_berserker: '/assets/characters/enemy_darkKnight.png',
  vampire_lord: '/assets/characters/enemy_darkKnight.png',
  dungeon_lord: '/assets/characters/enemy_boss_lich.png',
};

export const BACKGROUND_IMAGES = {
  campfire: '/assets/backgrounds/bg_campfire.png',
  dungeon_battle: '/assets/backgrounds/bg_dungeon_battle.png',
};
